name: CICD for PR to staging with yaml to GIT

on:
  pull_request:
    branches: [ staging ]

jobs:
  
  build:
    if: github.repository_owner == 'raul3520'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Super-Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: feature
        VALIDATE_ALL_CODEBASE: false
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_YAML: false
        VALIDATE_BASH: false
        
    - name: Build the Docker image and push yaml to repo
      run: |
          tag1="$(date '+%Y-%m')-${{ github.run_number }}"
          echo $tag1

    - name: Docker Login

      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
    
    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1.1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG}}
    
    
    - name: Build the Docker image and push yaml to repo
      run: |

        tag="$(date '+%Y-%m')-${GITHUB_SHA::8}"
        echo $tag
        docker build . --tag raul3520/mynewtest:$tag
        docker push raul3520/mynewtest:$tag

        echo "Tag at $tag"
        #kubectl apply -f k8s.yaml
        #sleep 18
        #sh k8monit.sh
        git config --global user.email "raul3520@gmail.com"
        git config --global user.name "raul3520"
        git remote set-url origin https://raul3520:${{ secrets.PAT}}@github.com/raul3520/yamlcode.git
        git clone https://raul3520:${{ secrets.PAT}}@github.com/raul3520/yamlcode.git
        
        sed -i "s/TAG/$tag/g" k8s.yaml

        cp k8s.yaml yamlcode/k8s.yaml 
        cd yamlcode
        git add k8s.yaml
        git commit -m "test"
        git push origin main
        

        




